name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  # Для проверки подключения к интернету.
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  # Для использования bloc, а также различных
  # виджетом по типу BlocBuilder, BlocProvider и тд.
  flutter_bloc: ^8.0.1
  # Для того чтобы делать различные запросы в сеть.
  http: ^0.13.4
  # Определяет аннотации, используемые json_serializable 
  # для создания кода для сериализации и десериализации JSON.
  json_annotation: ^4.5.0

dev_dependencies:
  # Чтобы сгенерировать что-либо
  build_runner: ^2.1.11
  # Дефолтный линтер от флатера
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
